apiVersion: v1
kind: ConfigMap
metadata:
  name: products-store-mssql-connection-configmap
data:
  db-connection-string: Server=products-store-mssql-service;Database=ProductsDB;User=sa;Password=@Aa123456;
