kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: products-store-ns
  name: products-store-mssql-sc
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: products-store-ns
  name: products-store-mssql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: products-store-mssql-sc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
