apiVersion: v1
kind: Secret
metadata:
  name: products-store-mssql-secret
data:
   db-connection-string-secret:  U2VydmVyPXByb2R1Y3RzLXN0b3JlLW1zc3FsLXNlcnZpY2U7RGF0YWJhc2U9UHJvZHVjdHNEQjtVc2VyPXNhO1Bhc3N3b3JkPUBBYTEyMzQ1Njs=
   db-password-secret:  QEFhMTIzNDU2
type: Opaque
